### ISSUE TITLE
Language management - iOS paywall

### ISSUE THREAD

**Issue by lopspower** [RevenueCat/purchases-kmp#173]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read
  the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched
  for [existing Github issues](https://github.com/RevenueCat/purchases-kmp/issues)

**Describe the bug**
I'm developing two applications with Kotlin multiplatform. Everything is well configured, I can see the paywall and I can subscribe on both platforms. However, on iOS, when I run the test on a French device, I see the English paywall (I don't have this problem on Android, I can see the French and English paywall depending on the language of my device.).
I've checked, my App Store is in French and my phone is in French too. The paywall is still displayed in English, even though it is configured in French on your platform. What's more, when I click to subscribe, the native Apple view is displayed in French. Which confirms what I said above.
I don't think the problem lies with the native SDK, but probably with this KMP library. Isn't there a configuration missing for language management on iOS?

1. Environment
    1. Platform: iOS
    2. SDK version: `1.0.0-beta.3` & `1.0.0-beta.2`
    3. OS version: iOS 17.6.1
    4. IDE (e.g. Android Studio, Xcode, Fleet): Xcode
    5. IDE version: Xcode
    6. Device and/or emulator/simulator:
        - [X] Device
        - [X] Emulator/simulator
    7. Environment:
        - [X] Closed testing / Sandbox
        - [X] TestFlight
        - [X] Production
    8. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to
   have context, eg. stackoverflow, etc.)

**Additional context**
I've contacted support with all the screenshots. I can't share the same screenshots here for privacy reasons.

**Comment by JayShortway** [comment]
Hi, thanks for reporting this! I can indeed reproduce this issue using `1.0.0-beta.3`. 

There were some recent fixes to our [purchases-ios SDK](https://github.com/RevenueCat/purchases-ios/pull/4158), which the purchases-kmp SDK transitively depends on. Those fixes seem to do the trick, as it fails to reproduce using the current head of `main` for me. That means this should be fixed in the upcoming `1.0.0` stable release of purchases-kmp. Should be any day now. 

Let me know if you have any other questions!

**Comment by JayShortway** [comment]
The [stable release](https://github.com/RevenueCat/purchases-kmp/releases/tag/1.0.0+13.2.0) was just published. Let me know if it's indeed fixed when you have time to update!

**Comment by lopspower** [comment]
I can confirm that it does fix the problem, thanks for your responsiveness.

**Comment by JayShortway** [comment]
Thanks for confirming, great to hear!
