### ISSUE TITLE
Namespace collision between :core and :models when uniquePackageNames is enabled

### ISSUE THREAD

**Issue by alaegin** [RevenueCat/purchases-kmp#185]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read
  the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched
  for [existing Github issues](https://github.com/RevenueCat/purchases-kmp/issues)

**Describe the bug**
With the release of 1.0.0 the `:models` module was added, however, the namespace in it is the same as in `:core` module. With the `android.uniquePackageNames=true` property this leads to an exception during the compilation of the Android app.

https://github.com/RevenueCat/purchases-kmp/blob/7c60a7131a5b7aa0476078ea7a86f7e6dd59de84/models/build.gradle.kts#L25

```
> Task :app-android:processDevDebugMainManifest FAILED
[com.revenuecat.purchases:purchases-kmp-core-android:1.0.0+13.2.0] /Users/alexey/.gradle/caches/8.8/transforms/61696659ac84c82bf00d9657d836fdb4/transformed/core-release/AndroidManifest.xml Error:
	Namespace 'com.revenuecat.purchases.kmp' is used in multiple modules and/or libraries: com.revenuecat.purchases:purchases-kmp-core-android:1.0.0+13.2.0, com.revenuecat.purchases:purchases-kmp-models-android:1.0.0+13.2.0. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace
/Users/alex/StudioProjects/own/xxx/app-android/src/main/AndroidManifest.xml Error:
	Validation failed, exiting

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.
```

The solution is to change the `namespace` accordingly to have a module name at the end like in other modules:
https://github.com/RevenueCat/purchases-kmp/blob/7c60a7131a5b7aa0476078ea7a86f7e6dd59de84/mappings/build.gradle.kts#L35

Our temporary fix is to disable `android.uniquePackageNames` property in out project.

1. Environment
    1. Platform: Android
    2. SDK version: 1.0.0
    3. OS version: macOS
    4. IDE (e.g. Android Studio, Xcode, Fleet):
    5. IDE version:
    6. Device and/or emulator/simulator:
        - [x] Device
        - [x] Emulator/simulator
    7. Environment:
        - [x] Closed testing / Sandbox
        - [x] TestFlight
        - [x] Production
    8. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
Not needed
4. Steps to reproduce, with a description of expected vs. actual behavior
You need to enable `android.uniquePackageNames` inside `gradle.properties` and build the android app.

**Comment by JayShortway** [comment]
TIL about `android.uniquePackageNames`, thanks for reporting this! We'll have a look at what the best course of action would be.

**Comment by JayShortway** [comment]
All the above PRs have been merged. This should be in the next release.

**Comment by JayShortway** [comment]
@alaegin Latest release just went out. I'd be curious to know if it fixes the issue for you, whenever you have some time!

**Comment by adrianegraphene** [comment]
Fixed the issue for me. I was having issues for the past few days on a new build. This was the last piece of the puzzle.

**Comment by alaegin** [comment]
Hello, @JayShortway!

Problem solved, thank you!

**Comment by JayShortway** [comment]
@alaegin @adrianegraphene Great to hear, thanks both for confirming!
