### ISSUE TITLE
Ios Paywall UI Stuck at when error occurs, and dismissRequest is not called

### ISSUE THREAD

**Issue by mirzemehdi** [RevenueCat/purchases-kmp#217]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read
  the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched
  for [existing Github issues](https://github.com/RevenueCat/purchases-kmp/issues)

**Describe the bug**
When using Paywall UI, and let's say there is some configuration issue. In both android and ios below message dialog is shown. When Clicking okay button, in android dismissRequest is called, but in ios it is not called. I would expect to have same behaviour as it is in android.

<img width="345" alt="image" src="https://github.com/user-attachments/assets/d9e6484f-dbe8-4838-80b0-89dcbb045d79">

1. Environment
    1. Platform: iOS
    2. SDK version: 1.0.0+13.2.0
    3. OS version:
    4. IDE (e.g. Android Studio, Xcode, Fleet):
    5. IDE version:
    6. Device and/or emulator/simulator:
        - [ ] Device
        - [x] Emulator/simulator
    7. Environment:
        - [x] Closed testing / Sandbox
        - [ ] TestFlight
        - [ ] Production
    8. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to
   have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by JayShortway** [comment]
Hi @mirzemehdi, thanks for reporting this! We'll look into it.

**Comment by JayShortway** [comment]
@mirzemehdi Quick update: the fix for this is in purchases-ios (PR linked above). Will have to get this propagated to purchases-kmp. Thanks again for reporting!

**Comment by JayShortway** [comment]
Hi @mirzemehdi, this should be fixed in `1.1.2+13.5.0`. Let me know how it works for you!

**Comment by mirzemehdi** [comment]
@JayShortway Amazing. Thank you very much. Just tested it, and it works as expected now.

**Comment by JayShortway** [comment]
Awesome, happy to hear that!
