### ISSUE TITLE
Support for Offerings.getCurrentOfferingForPlacement()

### ISSUE THREAD

**Issue by doolle89** [RevenueCat/purchases-kmp#242]
I saw that Offerings.getCurrentOfferingForPlacement(placementId: String) was removed in 1.0.0-beta.2, so I wander if there is some alternative way to use this feature? If not, is it going to be added back at some point and when it could be expected? 

Thanks in advance!

**Comment by JayShortway** [comment]
Hi, thanks for this request! 

It was removed, because it wasn't working on iOS. The intention is indeed to bring it back. I don't think there's another way to use this feature right now, but we'll have a look at what the best way would be to revive it.

**Comment by doolle89** [comment]
Thanks for looking into it so quickly!

**Comment by JayShortway** [comment]
@doolle89 No worries, happy to help! 

This has just been released in 1.2.0+13.6.0. Let me know how it works for you!

**Comment by doolle89** [comment]
@JayShortway I tested 1.2.0+13.6.0, Offerings.getCurrentOfferingForPlacement() works as expected :)

Thanks again!

**Comment by JayShortway** [comment]
@doolle89 Thanks for letting me know, happy to hear!
